
MOUSEKEY_ENABLE=yes
RGBLIGHT_ENABLE=no
RGB_MATRIX_ENABLE=no

RGBLIGHT_SUPPORTED=no
RGB_MATRIX_SUPPORTED=no

OLED_ENABLE=yes
OLED_TIMEOUT=10
COMBO_ENABLE=yes

BOOTMAGIC_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
AUDIO_ENABLE = no

LTO_ENABLE = yes

EXTRAFLAGS += -flto

LEADER_ENABLE = yes
TAP_DANCE_ENABLE = yes
