OLED_ENABLE=yes
OLED_TIMEOUT=10

BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = yes
AUDIO_ENABLE = no
RGB_MATRIX_ENABLE = no

LTO_ENABLE = yes

RGBLIGHT_SUPPORTED = no
RGB_MATRIX_SUPPORTED = no
EXTRAFLAGS += -flto

LEADER_ENABLE = yes
