OLED_ENABLE=yes
OLED_TIMEOUT=0

BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
AUDIO_ENABLE = no
RGB_MATRIX_ENABLE = no

RGBLIGHT_ENABLE = yes
RGBLIGHT_MODE_RAINBOW_MOOD=0
